### ISSUE TITLE
MinGW64 and Windows

### ISSUE THREAD

**Issue by Hurongo** [gorbatschow/ImOsmDemo#3]
when compiling, the compiler will throw an error:
 g++ main.cpp -o main -std=c++20 D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\imgui*.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_glfw.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_opengl3.cpp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imapp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imosm -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imosm\\include -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\implot -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap\\include -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\latlon -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imfonts -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\mini\\src\\mini -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\stb -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\glfw\\include\\GLFW -lglfw3 -lopenGL32
In file included from D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm/imosm.h:7,
                 from ImOsmDemoApp.h:3,
                 from main.cpp:1:
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm\include/ImOsmTile.h:14:23: error: conflicting return type specified for 'virtual std::size_t ImOsm::Tile::rawBlobSize() const'
   14 |   virtual std::size_t rawBlobSize() const override;
      |                       ^~~~~~~~~~~
In file included from D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm\include/ImOsmTile.h:2:
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm\include/ImOsmTileDummy.h:29:18: note: overridden function is 'virtual ImOsm::size_t ImOsm::TileDummy::rawBlobSize() const'
   29 |   virtual size_t rawBlobSize() const override { return 0; }
      |                  ^~~~~~~~~~~
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm\include/ImOsmTile.h:17:23: error: conflicting return type specified for 'virtual std::size_t ImOsm::Tile::rgbaBlobSize() const'
   17 |   virtual std::size_t rgbaBlobSize() const override;
      |                       ^~~~~~~~~~~~
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imosm\include/ImOsmTileDummy.h:33:18: note: overridden function is 'virtual ImOsm::size_t ImOsm::TileDummy::rgbaBlobSize() const'
   33 |   virtual size_t rgbaBlobSize() const override { return 0; }

can you help?

**Comment by ramgon** [comment]
Hi [Hurongo](https://github.com/Hurongo) 

Well, it seems like std::size_t is not the same as size_t, ok, i made a few changes in the code
https://github.com/gorbatschow/ImOsm/commit/b2ff613739ae204a496729b44e24ffe86b410c9b
and also updated submodule for this repo.

I'm currently using Linux  and have small experience in building imgui+glfw based applications on Windows only with Visual Studio compiler, but  for this case I think we will have an interesting trip related to libcurl :)

Have you already installed libcurl?

**Comment by Hurongo** [comment]
Good evening!)
When adding a library to a project, the error remains :(
I downloaded the code again, unfortunately it did not affect the error
I wonder what could be the reason...
I think it will be easier to download Linux on the computer : )

**Comment by ramgon** [comment]
Yeah, better try it on Linux, at least  I can confirm that it works on the latest Ubuntu and Mint and builds with clang compiler.
Please note I made changes in the branch named "fixes", not in the "master"
https://github.com/gorbatschow/ImOsm/tree/fixes

**Comment by Hurongo** [comment]
Good evening!)
after the correction, other links appeared(
D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\cc4yF8Lc.o:main.cpp:(.text+0x1a63b): undefined reference to `ImOsmDemoApp::ImOsmDemoApp()'

D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\cc4yF8Lc.o:main.cpp:(.text+0x1a647): undefined reference to `ImApp::MainWindow::run()'

D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\cc4yF8Lc.o:main.cpp:(.text+0x1a658): undefined reference to `ImOsmDemoApp::~ImOsmDemoApp()'

D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\cc4yF8Lc.o:main.cpp:(.text+0x1a66b): undefined reference to `ImOsmDemoApp::~ImOsmDemoApp()'


And this is already a better sign)

Please tell me what other libraries you use besides glfw3.dll?

**Comment by ramgon** [comment]
Well, it looks simply... like problems with build configuration, for example if no cpp files provided to compiler, but i think we need to go deeper.

I have a basic project, could you try to build it please?
https://github.com/gorbatschow/ImProject/tree/master

**Comment by Hurongo** [comment]
$ g++ mainn.cpp -o main -std=c++17 D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\imgui*.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_glfw.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_opengl3.cpp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\ImApp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\Imosm -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\Imosm\\include -ID:\\MinGW64\\mingw64\\include\\curl -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\implot -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap\\include -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\latlon -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\ImFonts -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\mINI\\src\\mini -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\stb -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\glfw\\include\\GLFW -LD:\\MinGW64\\mingw64\\bin -lglfw3
In file included from D:\MinGW64\home\38097\Test\ImOsmDemo\external\imwrap/imwrap.h:3,
                 from mainn.cpp:2:
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imwrap/include/ImWrapBasicElement.h: In member function 'virtual std::string ImWrap::BasicElement::elementIdStr() const':
D:\MinGW64\home\38097\Test\ImOsmDemo\external\imwrap/include/ImWrapBasicElement.h:27:10: error: 'erase_if' is not a member of 'std'; did you mean 'enable_if'?
   27 |     std::erase_if(labelId, [](const char c) {
      |          ^~~~~~~~
      |          enable_if

$ g++ mainn.cpp -o main -std=c++20 D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\imgui*.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_glfw.cpp D:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends\\imgui_impl_opengl3.cpp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui\\backends -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imgui -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\ImApp -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\Imosm -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\Imosm\\include -ID:\\MinGW64\\mingw64\\include\\curl -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\implot -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\imwrap\\include -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\latlon -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\ImFonts -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\mINI\\src\\mini -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\stb -ID:\\MinGW64\\home\\38097\\Test\\ImOsmDemo\\external\\glfw\\include\\GLFW -LD:\\MinGW64\\mingw64\\bin -lglfw3
D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\ccv0iRRX.o:mainn.cpp:(.text+0x1a6ac): undefined reference to `ImApp::MainWindow::run()'
D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\ccv0iRRX.o:mainn.cpp:(.text$_ZN10ProjectAppC1Ev[_ZN10ProjectAppC1Ev]+0x42): undefined reference to `ImApp::MainWindow::MainWindow(std::__cxx11::basic_str
ing<char, std::char_traits<char>, std::allocator<char> > const&)'
D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\ccv0iRRX.o:mainn.cpp:(.text$_ZN10ProjectAppC1Ev[_ZN10ProjectAppC1Ev]+0x9b): undefined reference to `ImApp::MainWindow::~MainWindow()'
D:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MinGW64\tmp\ccv0iRRX.o:mainn.cpp:(.text$_ZN10ProjectAppD1Ev[_ZN10ProjectAppD1Ev]+0x32): undefined reference to `ImApp::MainWindow::~MainWindow()'
collect2.exe: error: ld returned 1 exit status

Please note that different versions of the c++ standard were used during compilation

**Comment by ramgon** [comment]
Well this error happened because compiler does not support new C++ features, it can be replaced by something like this `vec.erase(std::remove_if(vec.begin(), vec.end(), predicate), vec.end());`
but, you are using the newer version of ImWrap library, and it seems you downloaded all that stuff manually or (maybe updated), that is wrong way. Use git from terminal:
`git clone git@github.com:gorbatschow/ImOsmDemo.git`
than change dir to ImOsmDemo  and do
`git submodule update --init --recursive`

**Comment by Hurongo** [comment]
HI!)
i came back with linux on board, but when building with cmake:

zendor@zendor:~/IMGUI/ImOsmDemo/src$ mkdir build
zendor@zendor:~/IMGUI/ImOsmDemo/src$ cd build
zendor@zendor:~/IMGUI/ImOsmDemo/src/build$ cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is Clang 11.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zendor/IMGUI/ImOsmDemo/src/build
zendor@zendor:~/IMGUI/ImOsmDemo/src/build$ make
Scanning dependencies of target ImOsmDemoExe
[ 33%] Building CXX object CMakeFiles/ImOsmDemoExe.dir/main.cpp.o
In file included from /home/zendor/IMGUI/ImOsmDemo/src/main.cpp:1:
/home/zendor/IMGUI/ImOsmDemo/src/./ImOsmDemoApp.h:2:10: fatal error: 'imapp.h' file not found
#include <imapp.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/ImOsmDemoExe.dir/build.make:82: CMakeFiles/ImOsmDemoExe.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/ImOsmDemoExe.dir/all] error 2
make: *** [Makefile:103: all] error 2

cmake File:

cmake_minimum_required(VERSION 3.16.0)

project(ImOsmDemoExe)

set(CXX_CMAKE_STANDARD 20)
set(CXX_CMAKE_STANDARD_REQUIRED ON)

set(IMPROJECTEXE_SRC
    main.cpp
    ImOsmDemoApp.cpp
)

add_executable(${PROJECT_NAME} ${IMPROJECTEXE_SRC})
target_include_directories(${PROJECT_NAME} PUBLIC .)
target_link_libraries(${PROJECT_NAME} PUBLIC mini)
target_link_libraries(${PROJECT_NAME} PUBLIC imapp)
target_link_libraries(${PROJECT_NAME} PUBLIC imosm)
target_link_libraries(${PROJECT_NAME} PUBLIC imwrap)

I'm new to working with him, tell me something?

**Comment by Hurongo** [comment]
But all libraries are successfully installed

**Comment by ramgon** [comment]
Hi!
You don't need to install libraries, you don't have to do anything manually.
Look it's very simple:

0. Open a terminal
1. Clone
`git clone git@github.com:gorbatschow/ImOsmDemo.git`
2. Go to ImOsmDemo
`cd ImOsmDemo`
3. Update Submodules
`git submodule update --init --recursive`
4. Create a new build directory
`mkdir build`
5. Go to the build directory
`cd build`
6. Run CMake
`cmake ..`
!two points at the end are needed!
7. Run Make
`make`
8. Go to src folder
`cd src`
9. Run application
`./ImOsmDemoExe`

**Comment by Hurongo** [comment]
Dude, I don't know but it works!))
You are a wizard from Hogwarts)

I first tried to do this with a version cmake of 3.18.4
But it started only when I manually updated to the version 3.27.1
Thank you for such a monumental work!)

**Comment by ramgon** [comment]
Nice! I am happy to hear it :)
